# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  GitUser: 'donet-feats'
  GitEmail: 'notyetcrazymimi@gmai.com'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  LastCommit: $SYSTEM_PULLREQUEST_SOURCECOMMITID

steps:

- checkout: self
  persistCredentials: true

- task: NuGetToolInstaller@1
  displayName: 'Installing nuget tooling'

- task: CmdLine@2
  displayName: "Git profile"
  inputs:
    script: |
      git config --global user.email "$(GitEmail)"
      git config --global user.name "$(GitUser)"
    failOnStderr: true

- bash: |
    GITCOMMIT=$(git rev-parse HEAD)
    echo "##vso[task.setvariable variable=LastCommit]$GITCOMMIT"
  displayName: Set new variable value
  condition: and(succeeded(), eq(variables.isMain, true))
  
- script: |
    echo $(LastCommit)
  name: "CurrentLastCommit"

- task: gitversion/setup@0
  displayName: 'Installing Git version'
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: 'Version'
  name: Version

- task: DotNetCoreCLI@2
  displayName: 'tests'
  inputs:
    command: 'test'
    projects: 'feats.sln'
    testRunTitle: 'all tests'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutput=$(Build.SourcesDirectory)/CoverageResults/ /p:MergeWith=$(Build.SourcesDirectory)/CoverageResults/coverage.json /p:CoverletOutputFormat=json%2ccobertura -m:1'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/CoverageResults/**.cobertura.xml'

- task: DockerInstaller@0
  name: 'installDockerCli'
  inputs:
    dockerVersion: '17.09.0-ce'
  condition: and(succeeded(), eq(variables.isMain, true))

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker build -t "feats.evaluations:$(GitVersion.SemVer)" -f Dockerfile.evaluations .
    failOnStderr: true
  name: 'BuildEvalDockerfile'
  displayName: 'Build feats.evaluations dockerfile'
  condition: and(succeeded(), eq(variables.isMain, true))
# todo push to registry

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker build -t "feats.management:$(GitVersion.SemVer)" -f Dockerfile.management .
    failOnStderr: true
  name: 'BuildMgmtDockerfile'
  displayName: 'Build feats.management dockerfile'
  condition: and(succeeded(), eq(variables.isMain, true))
# todo push to registry

- task: CmdLine@2
  displayName: "Tagging version"
  inputs:
    script: |
      git tag -a "v$(GitVersion.SemVer)" -m "v$(GitVersion.SemVer)" "$(LastCommit)"
      git push origin "v$(GitVersion.SemVer)"
    failOnStderr: false
  condition: and(succeeded(), eq(variables.isMain, true))

